### ISSUE TITLE
Nécessité du "Project Creation path"

### ISSUE THREAD

**Issue by Simon-Belanger** [JonathanCauchon/ULaval_PDK_Development#12]
Quand on crée un nouveau projet, il faut spécifier un path. Les fichiers sont créés et les librairies sont instanciées dans ce path, ils sont ensuite push sur github et après on supprime la copie locale. Est-ce que c'est bien ça?

Dans ce cas quelle est la nécessité de fournir un path si ce n'est que temporaire?

<img width="454" alt="Screen Shot 2019-03-27 at 11 00 17 AM" src="https://user-images.githubusercontent.com/33395714/55089187-68298480-5083-11e9-8e69-e93a60ffcb68.png">

**Comment by JonathanCauchon** [comment]
Initialement le but était de create,  push to github, delete le directory local, et ensuite cloner la bonne branche correspondant à l'utilisateur.
La dernière étape est manquante ici

La plupart des issues sont NewProjectGUI-related j'ai l'impression alors dans l'implémentation Klayout je vais essayer de garder les methodes plus straight forward et robustes..
